#!/bin/bash

#controllo che ci sia la cartella config
#[[ -f ~/.config ]] && rm -rf ~/.config

#rimuovo i file vecchi
[[ -f ~/.vimrc ]] && rm ~/.vimrc
[[ -f ~/.vim ]] && rm -rf ~/.vim
[[ -f ~/.bashrc ]] && rm ~/.bashrc
[[ -f ~/.fzf.bash ]] && rm ~/.fzf.bash
[[ -f ~/.emoji-alias.bash ]] && rm ~/.emoji-alias.bash
[[ -f ~/.config/nvim ]] && rm -rf ~/.config/nvim
[[ -f ~/nvim ]] && rm -rf ~/nvim
[[ -f ~/.config/kitty ]] && rm -rf ~/.config/kitty
[[ -f ~/.config/topgrade.toml ]] && rm ~/.config/topgrade.toml
[[ -f ~/.config/hypr ]] && rm -rf ~/.config/hypr
[[ -f ~/.config/noctalia ]] && rm -rf ~/.config/noctalia
[[ -L ~/.config/niri ]] && rm ~/.config/niri
[[ -d ~/.config/niri ]] && rm -rf ~/.config/niri
[[ -f ~/.config/starship.toml ]] && rm ~/.config/starship.toml
[[ -L ~/.config/fastfetch ]] && rm ~/.config/fastfetch
[[ -d ~/.config/fastfetch ]] && rm -rf ~/.config/fastfetch

#li ricostruisco facendo dei link simbolici
ln -s ~/Dotfiles/vim ~/.vim
ln -s ~/Dotfiles/bashrc ~/.bashrc
ln -s ~/Dotfiles/fzf.bash ~/.fzf.bash
ln -s ~/Dotfiles/emoji-alias.bash ~/.emoji-alias.bash
ln -s ~/Dotfiles/nvim ~/.config
ln -s ~/Dotfiles/config/kitty ~/.config
ln -s ~/Dotfiles/config/topgrade.toml ~/.config
ln -s ~/Dotfiles/config/hypr ~/.config
ln -s ~/Dotfiles/config/noctalia ~/.config
ln -s ~/Dotfiles/config/niri ~/.config
ln -s ~/Dotfiles/config/starship/starship.toml ~/.config/starship.toml
ln -s ~/Dotfiles/config/fastfetch ~/.config/fastfetch

#installa vimplug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#installa YCM
# sudo apt install python3-dev cmake
# cd ~/.vim/plugged/YouCompleteMe
# ./install.py
# cd $HOME

#installa fzf
[[ -d $HOME/.fzf ]] || (echo "Installing fzf... " && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install)

#configurazione i3
if [ "$DESKTOP_SESSION" = "i3" ]; then
    # i3 config
    [[ -f ~/.config/i3 ]] && rm -rf ~/.config/i3
    [[ -f ~/.config/polybar ]] && rm -rf ~/.config/polybar
    [[ -f ~/.config/rofi ]] && rm -rf ~/.config/rofi

    ln -s ~/Dotfiles/config/i3 ~/.config/i3
    ln -s ~/Dotfiles/config/polybar ~/.config/polybar 
    # install font
    cp -r config/polybar/fonts/* ~/.local/share/fonts
    fc-cache -v
    sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf 
    ln -s ~/Dotfiles/config/rofi ~/.config/rofi
    i3 reload
    #set timezone
    sudo rm -rf /etc/localtime
    sudo ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime
    #i3 blocks config
    ## mkdir ~/.i3blocks
    #ln -s ~/Dotfiles/i3/i3blocks.conf ~/.i3blocks/config
    #i3blocks -c ~/.i3blocks/config
    #i3-msg restart
    ## download i3 scripts
    #rm -rf ~/.config/i3blocks
    #git clone https://github.com/vivien/i3blocks-contrib ~/.config/i3blocks
    #cd  ~/.config/i3blocks
    #for i in * 
    #do
    #    chmod +x "$i"/"$i" 
    #done
    #make install
    #cd ..
    #rm -rf i3blocks
    #i3-msg restart
    

     
fi

#if [ "$DESKTOP_SESSION" = "gnome" ]; then
#
#    # dconf load /org/gnome/shell/keybindings/ < gnome-keybindings 
#    # dconf dumpo /org/gnome/shell/keybindings/ > gnome-keybindings 
#fi

echo "Open vim and digit ':PlugInstall'"
# symlink local bin and applications
mkdir -p ~/.local/bin ~/.local/share/applications
ln -sf ~/Dotfiles/local/bin/kitty-browser.sh ~/.local/bin/kitty-browser.sh
chmod +x ~/.local/bin/kitty-browser.sh
ln -sf ~/Dotfiles/local/share/applications/kitty-browser.desktop ~/.local/share/applications/kitty-browser.desktop

#mette vim come editor predefinito
xdg-mime default vim.desktop text/*

# mette kitty come browser predefinito
xdg-settings set default-web-browser kitty-browser.desktop
xdg-mime default kitty-browser.desktop x-scheme-handler/http x-scheme-handler/https
source $HOME/.bashrc

echo ""
echo "NOTA: per installare niri e noctalia esegui: ./install-niri"


