#!/bin/bash

#controllo che ci sia la cartella config
[[ -f ~/.config ]] && rm -rf ~/.config

#rimuovo i file vecchi
[[ -f ~/.vimrc ]] && rm ~/.vimrc
[[ -f ~/.vim ]] && rm -rf ~/.vim
[[ -f ~/.bashrc ]] && rm ~/.bashrc
[[ -f ~/.fzf.bash ]] && rm ~/.fzf.bash
[[ -f ~/.emoji-alias.bash ]] && rm ~/.emoji-alias.bash
[[ -f ~/.config/nvim ]] && rm -rf ~/.config/nvim
[[ -f ~/.config/kitty ]] && rm -rf ~/.config/kitty
[[ -f ~/.config/topgrade.toml ]] && rm ~/.config/topgrade.toml

#li ricostruisco facendo dei link simbolici
ln -s ~/Dotfiles/vim ~/.vim
ln -s ~/Dotfiles/bashrc ~/.bashrc
ln -s ~/Dotfiles/fzf.bash ~/.fzf.bash
ln -s ~/Dotfiles/emoji-alias.bash ~/.emoji-alias.bash
ln -s ~/Dotfiles/nvim ~/.config
ln -s ~/Dotfiles/kitty ~/.config
ln -s ~/Dotfiles/topgrade.toml ~/.config

#installa vimplug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

#installa YCM
# sudo apt install python3-dev cmake
# cd ~/.vim/plugged/YouCompleteMe
# ./install.py
# cd $HOME

#installa fzf
[[ -d $HOME/.fzf ]] || (echo "Installing fzf... " && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install)

#configurazione i3
if [ "$DESKTOP_SESSION" = "i3" ]; then
    # i3 config
    [[ -f ~/.config/i3 ]] && rm -rf ~/.config/i3
    [[ -f ~/.config/polybar ]] && rm -rf ~/.config/polybar
    [[ -f ~/.config/rofi ]] && rm -rf ~/.config/rofi

    ln -s ~/Dotfiles/config/i3 ~/.config/i3
    ln -s ~/Dotfiles/config/polybar ~/.config/polybar 
    # install font
    cp -r config/polybar/fonts/* ~/.local/share/fonts
    fc-cache -v
    sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf 
    ln -s ~/Dotfiles/config/rofi ~/.config/rofi
    i3 reload
    #set timezone
    sudo rm -rf /etc/localtime
    sudo ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime
    #i3 blocks config
    ## mkdir ~/.i3blocks
    #ln -s ~/Dotfiles/i3/i3blocks.conf ~/.i3blocks/config
    #i3blocks -c ~/.i3blocks/config
    #i3-msg restart
    ## download i3 scripts
    #rm -rf ~/.config/i3blocks
    #git clone https://github.com/vivien/i3blocks-contrib ~/.config/i3blocks
    #cd  ~/.config/i3blocks
    #for i in * 
    #do
    #    chmod +x "$i"/"$i" 
    #done
    #make install
    #cd ..
    #rm -rf i3blocks
    #i3-msg restart

     
fi

echo "Open vim and digit ':PlugInstall'"
#mette vim come editor predefinito
xdg-mime default vim.desktop text/*
source $HOME/.bashrc
