color0 #18120f
color1 #ffb4ab
color2 #ffb687
color3 #e5bfa8
color4 #caca93
color5 #ffb687
color6 #e5bfa8
color7 #ece0da
color8 #9f8d83
color9 #ffb4ab
color10 #ffb687
color11 #e5bfa8
color12 #caca93
color13 #ffb687
color14 #e5bfa8
color15 #ece0da

cursor                #ece0da
cursor_text_color     #18120f
background            #18120f
foreground            #ece0da
selection_foreground  #d7c3b8
selection_background  #52443c
active_border_color   #ffb687
inactive_border_color #52443c
url_color             #ffb687

active_tab_foreground   #512400
active_tab_background   #ffb687
inactive_tab_foreground #d7c3b8
inactive_tab_background #52443c
cursor_trail_color      #d7c3b8
