# ~/.config/kitty/kitty.conf

# FONT
font_size       12.0
font_family     FiraMono Nerd Font Mono

# SCOLLBAR
scrollback_lines 200000

 #WINDOW LAYOUT
remember_window_size   yes

# THEME
include ./nord.conf
# include ./catppuccin.conf

linux_display_server wayland

# WAYLAND / GNOME INTEGRATION
# Usa le decorazioni del compositor (GNOME/Mutter) invece di quelle di Kitty
# In questo modo la titlebar avrà lo stesso stile GTK del tema Yaru-red
wayland_titlebar_color #ebebeb

# KEYBOARD SHORTCUT

